//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using library_system.Models;

namespace library_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class library_systemEntities2 : DbContext
    {
        public library_systemEntities2()
            : base("name=library_systemEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author_details> author_details { get; set; }
        public virtual DbSet<category_details> category_details { get; set; }
        public virtual DbSet<master_book_information> master_book_information { get; set; }
        public virtual DbSet<sub_category> sub_category { get; set; }
    
        public virtual ObjectResult<SelectallBooks_Result> SelectallBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectallBooks_Result>("SelectallBooks");
        }
    }
}
