//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace library_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_book_information
    {
        public int id { get; set; }
        public string isbn { get; set; }
        public string book_name { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> sub_category_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<System.DateTime> published_year { get; set; }
    
        public virtual author_details author_details { get; set; }
        public virtual category_details category_details { get; set; }
        public virtual sub_category sub_category { get; set; }
    }
}
